### ISSUE TITLE
acid-state with newer Stackage LTS?

### ISSUE THREAD

**Issue by CSchank** [acid-state/acid-state#114]
Hi,

Someone has asked this back in September 2017, but nothing seems to have come from it: how can we use `acid-state` with LTS Haskell > 8.24? We're fine to stick to this version for now, but it would be nice to upgrade for us to newer GHC versions eventually.

Thanks so much!

**Comment by adamgundry** [comment]
AFAIK `acid-state` should work fine with newer Stackage LTS versions (please file a bug if not). If you are using `stack` you will need to add `acid-state` to the `extra-deps` section of your `stack.yaml`, but that's about it.

**Comment by mihaimaruseac** [comment]
Would be easy to add it to Stackage if someone makes PRs against stackage.

**Comment by adamgundry** [comment]
I'm prepared to add it but I've got some significant reorganisation planned (including splitting out multiple packages, see #99) that I think should happen first.

**Comment by CSchank** [comment]
You are correct, it does work. I just tested with LTS 12.20. Apologies. The first time we tried adding `acid-state` to our project, we had problems with other packages we thought were related to `acid-state`. It was just our own inexperience with `stack` I think (we had just migrated from using `cabal build` to build our project). Thanks for getting back to us so quickly. Best regards.

**Comment by adamgundry** [comment]
Thanks for confirming. I'll close this issue and we can track adding `acid-state` to Stackage on #87.
