### ISSUE TITLE
Hackage release needed for GHC 9.0.2 support

### ISSUE THREAD

**Issue by luntain** [acid-state/acid-state#137]
Looks like @funketh contributed changes for ghc 9.0.2 support, which were merged into master by @ddssff. The current version on Hackage fails compilation in ghc 9.0.2, a new Hackage release is needed.

https://github.com/acid-state/acid-state/commit/a42ef66369f38925e33c47e2f33365076eca3b1b

**Comment by andreasabel** [comment]
See also (for a CI):
- #140

**Comment by ddssff** [comment]
Version 0.16.1 uploaded to hackage.
