### ISSUE TITLE
Database seems empty after ctrl+c

### ISSUE THREAD

**Issue by YellowOnion** [acid-state/acid-state#147]
I've made a simple pastebin using Acid State and it seems to work fine until I ctrl+c, once it's reloaded it seems to be empty. The event-*.log files have the pasted contents still inside so I'm not sure why Acid state can't find the stored keys?

Here's the code: https://gist.github.com/YellowOnion/c7f45383753b267f7ffe05b1dd25341e

Am I miss understanding what to pass to openLocalState on second mount and it's using the new SipKey?

**Comment by stepcut** [comment]
Nothing appears to be wrong with the code you shared or your expectations about how things should work.

When you run the code a second time, does it start overwriting the old event files or does it pickup where it left off and start adding more event files after the existing ones? 

How are you determining that the database is empty? I only see two functions -- `insertFile`, which returns an `ID` and `lookupFile` which looks up an `File` by that `ID`. But.. how do you store the IDs across multiple invocations?

I would write a query function like:

```
dumpStore :: Query Store Store
dumpStore = ask
```

Which just returns the entire state so you can print it out and see what is actually in the store.

**Comment by YellowOnion** [comment]
Okay thanks for the tip, I ran dump, and all the entries are there, but the IDs are different, are initial values run every time, not just on original database creation? I noticed the sk and other default values (like Map.empty) ale not stored anywhere inside the event file, just an abstract insert event.

**Comment by adamgundry** [comment]
Is this the same issue as #20?

**Comment by YellowOnion** [comment]
Yeah it is.
