### ISSUE TITLE
Benchmarks fail to build on GHC 9.8 due to `system-filepath`

### ISSUE THREAD

**Issue by andreasabel** [acid-state/acid-state#164]
Benchmarks fail to build on GHC 9.8 due to `system-filepath` so they are disabled in CI for GHC 9.8.
 
`system-filepath` has bound `deepseq < 1.5`:
https://github.com/acid-state/acid-state/actions/runs/6478328453/job/17589920578#step:15:29
- https://github.com/acid-state/acid-state/pull/163

Upstream issue:
- [x] https://github.com/fpco/haskell-filesystem/issues/28

**Comment by ddssff** [comment]
The package seems to build and test fine without the system-filepath dependency.
