### ISSUE TITLE
createArchive moves everything into the Archive folder if no checkpoint is present and may cause data loss

### ISSUE THREAD

**Issue by ozataman** [acid-state/acid-state#22]
This could easily cause permanent data loss if the user then proceeds to remove the Archive folder, which is claimed to be safe by the documentation.

A solution may be to have createArchive implicitly create a checkpoint when called.

**Comment by mf59816** [comment]
Is this issue still unresolved?

**Comment by Lemmih** [comment]
I think I meant to do something about this and then completely forgot. Will check again.

**Comment by oxij** [comment]
Any progress?

**Comment by damiencourousse** [comment]
I am also hit by this bug, and this is a show-stopper for me.
I modified the example 'SlowCheckpoint' [here](https://github.com/damiencourousse/acid-state/commit/478de71b5dbe3818ff7acfc3548695ee0df1c04c) to provide a reproducible case.

best regards,
Damien
