### ISSUE TITLE
BlockedIndefinitelyOnMVar on GHC 7.8

### ISSUE THREAD

**Issue by meteficha** [acid-state/acid-state#55]
(I know I may be asking a bit too much on this issue, please let me know if I should close it and look for help elsewhere.)

I'm setting up Travis-CI for the yesodweb/serversession repo and I just got this:

```
Failures:

  1) AcidStorage on local storage stress test: one 100 MiB value

       uncaught exception: BlockedIndefinitelyOnMVar (thread blocked indefinitely in an MVar operation)

  2) AcidStorage on local storage stress test: one 1 MiB key

       uncaught exception: BlockedIndefinitelyOnMVar (thread blocked indefinitely in an MVar operation)

  3) AcidStorage on local storage stress test: key with all possible Unicode code points and value with all possible byte values

       uncaught exception: BlockedIndefinitelyOnMVar (thread blocked indefinitely in an MVar operation)
```

(Source: https://travis-ci.org/yesodweb/serversession/jobs/64816620#L1305)

These tests worked fine for `acid-state` using the Memory storage.  These also work fine on my machine.  I've ran this test many times already and I've never seen `BlockedIndefinitelyOnMVar`.  Also, I've tried googling "acid-state BlockedIndefinitelyOnMVar" and didn't find anything relevant.

So, any thoughts about what could be causing this?  Anything I could do to help debug it?

**Comment by meteficha** [comment]
I forgot to mention that the failed test was built with GHC 7.8.4.  The Travis build from the same commit using GHC 7.10.1 [passed](https://travis-ci.org/yesodweb/serversession/jobs/64816622#L1316).

**Comment by meteficha** [comment]
There definitely is something fishy going on with GHC 7.8.  While [GHC 7.10 is able to finish my test suite using 600 MiB](https://travis-ci.org/yesodweb/serversession/jobs/64858947#L1268), I can't make GHC 7.8 work [because not even 2 GiB is enough for it](https://travis-ci.org/yesodweb/serversession/jobs/64858946#L1298) and Travis "only" allows 3 GiB (note that the process was killed before GHC could print statistics).

Is it known that GHC 7.8 requires a lot more memory than GHC 7.10?  The other related packages on the same build work fine on both 7.8 and 7.10, leading me to assume it isn't a mistake [on my code](https://github.com/yesodweb/serversession/blob/master/serversession-backend-acid-state/src/Web/ServerSession/Backend/Acid/Internal.hs).

**Comment by sdx23** [comment]
Just a guess, as I'm not aware of how Travis does this: If they handle disk-storage as a tmpfs the overall memory-usage may be too high with GHC 7.8 and as a result the thing run out of "disk space".

If you have the time, please check whether pull-request #58 fixes this for you. (should still fail, but not hanging in an MVar operation)

**Comment by adamgundry** [comment]
This issue is now rather old and it sounds like it was only observed on GHC 7.8 in particular circumstances, so I'm closing. Feel free to reopen if you have further information or think this is still a problem.
