### ISSUE TITLE
The constraints in the `Method` class are unnecessary

### ISSUE THREAD

**Issue by bitemyapp** [acid-state/acid-state#57]
https://github.com/acid-state/acid-state/blob/master/src/Data/Acid/Core.hs#L77-L85

Could get moved out to a function like `defaultMethodTag :: Typeable ev => ev -> Tag` so that you're not forcing end-users to use Typeable when they do not want to.

**Comment by adamgundry** [comment]
Fixed by #96. The `Method` class no longer has `Typeable` as a superclass, instead `methodTag` uses a default signature.
