### ISSUE TITLE
Add changelog to package for use on Hackage

### ISSUE THREAD

**Issue by axman6** [acid-state/acid-state#77]
Now there's a changelog being maintained, it'd be nice to have it included with the release. According to http://stackoverflow.com/questions/21076759/how-to-add-a-changelog-to-a-cabal-package all that's needed is 
```
Extra-Source-Files:  changelog.md
```

**Comment by stepcut** [comment]
It appears we already have that:

https://github.com/acid-state/acid-state/blob/master/acid-state.cabal#L14

What seems to be the issue?

**Comment by axman6** [comment]
Oh my mistake, I completely missed it on Hackage, despite looking for it!
