### ISSUE TITLE
seize.it is down - deadlinks

### ISSUE THREAD

**Issue by sdx23** [acid-state/acid-state#78]
Seemingly seize.it is down, so both the homepage link and the examples reference in Hackage don't work anymore.

**Comment by domenkozar** [comment]
@Lemmih

**Comment by Lemmih** [comment]
The links should be updated to point to articles hosted here on github.

**Comment by adamgundry** [comment]
Looks like this was fixed in b388af234125802fca6557d2cbca219ca6170724
