### ISSUE TITLE
Very slow loading of state?

### ISSUE THREAD

**Issue by o1lo01ol1o** [acid-state/acid-state#80]
I have an acid-state db of a string-record  key/value store that is several million entries and about 2gb on disk.  I checkpointed right after creation, however, the state takes about 20 minutes to load into ram and it seems to consume 11gb during this process (after which it returns to ~2gb). 

The record data type is 
```
data R = R {
    a       :: [Maybe (Text)],
    b     :: Maybe (Text),
    c      :: Maybe (Text),
    d     :: Maybe (Text),
    e   :: Maybe (Text),
    f       :: [[(Maybe Text)]],
    g       :: [Maybe (Text)],
    h :: [[(Maybe Text)]],
    i    :: ReleaseId,
    j  :: [Maybe (Text)]
  } deriving (Show,Eq,Generic)

```

Can I optimize this somehow?

**Comment by dmjio** [comment]
Linked lists in general are a very inefficient data structure. I'd recommend replacing your usage of lists with vectors from this package https://hackage.haskell.org/package/vector

**Comment by o1lo01ol1o** [comment]
I suspected as much. Thanks for the quick reply!
