### ISSUE TITLE
signalProcess: permission denied (Operation not permitted)

### ISSUE THREAD

**Issue by cleverca22** [acid-state/acid-state#92]
`cardano-node: signalProcess: permission denied (Operation not permitted)`

by random chance, the pid in the `open.lock` file got reused by a kernel thread
and lacking permission to send it a null signal, acid-state now throws an exception and is unable to start

i believe i am using rev https://github.com/acid-state/acid-state/commit/95fce1dbada62020a0b2d6aa2dd7e88eadd7214b which doesnt seem to be in any branch?
edit: ah, its master on serokell's fork: https://github.com/serokell/acid-state/commit/95fce1dbada62020a0b2d6aa2dd7e88eadd7214b

@neongreen

**Comment by neongreen** [comment]
This should actually be fixed here: https://github.com/acid-state/acid-state/pull/91. After that we probably won't be using our own fork (?)

**Comment by adamgundry** [comment]
Now that #91 is merged I believe this should be fixed.
